insert into Gerencia (gerencia)
values 
('Analista em Gestão Administrativa'),
('Apoio Gabinete'),
('Assessoria Jurídica'),
('Central Telefônica'),
('Gabinete do Secretário'),
('Gerência Administrativa Financeira'),
('Gerência de Acompanhamento de Editais'),
('Gerência de Apoio Jurídico'),
('Gerência de Arquitetura e Engenharia'),
('Gerência de Atendimento ao Cidadão'),
('Gerência de Atendimento ao Servidor'),
('Gerência de Cadastro de Fornecedores'),
('Gerência de Compras do Estado'),
('Gerência de Compras Eletrônicas'),
('Gerência de Comunicação'),
('Gerência de Contratos'),
('Gerência de Desenvolvimento de Pessoas'),
('Gerência de Educação Corporativa'),
('Gerência de Licitações'),
('Gerência de Patrimônio do Estado'),
('Gerência de Pessoas '),
('Gerência de Programação Orçamentária'),
('Gerência de Projetos'),
('Gerência de Tecnologia da Informação'),
('Gerência Financeira de Pessoal do Estado'),
('Gerência Geral de Folha de Pagamento do Estado'),
('Gerência Geral de Infraestrutura '),
('Gerência Geral de Licitações'),
('Gerência Geral de Planejamento e Gestão'),
('Gerência Geral de Política de Pessoal'),
('Gerência Geral Jurídica'),
('Gerência Orçamentária Financeira'),
('Unidade de Almoxarifado'),
('Unidade de Comunicação e Documentação'),
('Unidade de Transporte'),
('Unidade de Compras'),
('Ouvidoria da SAD'),
('Recepção'),
('Secretaria Executiva - SEPRI'),
('Secretaria Executiva de Administração'),
('Secretaria Executiva de Licitações'),
('Superintendência de Gestão'),
('Superintendência de Modernização Governamental'),
('Superintendência Técnica'),
('Núcleo de Gestão Imobiliário'),
('NIERH');