/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Usuario;

import Geral.Fachada;
import Login.LoginUser;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author airton.oliveira
 */
public class ObsAlterar extends javax.swing.JFrame {

    /**
     * Creates new form ObsAlterar
     */
    public ObsAlterar() {
        initComponents();
    }
    
    //private Usuario user;
    private Obs selecionadoObs;
    private LoginUser logado;
    
     void icone() {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("src\\resources\\favicon-cor.png"));
            this.setIconImage(img);
        } catch (IOException e) {
        }
    }
    
    public ObsAlterar(Obs selecionadoObs){
     
     initComponents();   
     setLocationRelativeTo(null); 
     setTitle("Alterar observação");
     //this.user=user;
     
     this.selecionadoObs=selecionadoObs;
     
     jLabelCONFIG.setText("Configuração:"+selecionadoObs.getUsuario_obs().getConfigMicro().getConfiguracao());
     jLabelGARANTIA.setText("Garantia: "+selecionadoObs.getUsuario_obs().getGarantia());
     jLabelGERENCIA.setText("Gerência: "+selecionadoObs.getUsuario_obs().getGerencia().getGerencia());
     jLabelHOST.setText(selecionadoObs.getUsuario_obs().getNomepc());
     jLabelMODELO_MICRO.setText("Modelo do Micro: "+selecionadoObs.getUsuario_obs().getModeloMicro().getModelo());
     jLabelMODELO_MONITOR.setText("modelo do Monitor: "+selecionadoObs.getUsuario_obs().getModeloMonitor().getModelo());
     jLabelPAVIMENTO.setText("Pavimento: "+selecionadoObs.getUsuario_obs().getPavimentoUsuario().getPavimento());
     jLabelPLATAFORMA.setText("Plataforma: "+selecionadoObs.getUsuario_obs().getPlataformaMicro().getPlataforma());
     jLabelSERIE_MICRO.setText("Série do Micro: "+selecionadoObs.getUsuario_obs().getSerieMicro());
     jLabelSERIE_MONITOR.setText("Série do Monitor: "+selecionadoObs.getUsuario_obs().getSerieMonitor());
     jLabelTOMBO_MICRO.setText("Tombamento do Micro: "+selecionadoObs.getUsuario_obs().getTombamentoMicro()+"");
     jLabelTOMBO_MONITOR.setText("Tombamento do Monitor: "+selecionadoObs.getUsuario_obs().getTombamentoMonitor()+"");
     
     TextAreaOBS.setText(selecionadoObs.getObs());
             
    }
    
    public ObsAlterar(Obs selecionadoObs,LoginUser logado){
        icone();
     initComponents();   
     setLocationRelativeTo(null); 
     setTitle("Alterar observação");
     //this.user=user;
     
     this.selecionadoObs=selecionadoObs;
     this.logado=logado;
     jLabelCONFIG.setText("Configuração:"+selecionadoObs.getUsuario_obs().getConfigMicro().getConfiguracao());
     jLabelGARANTIA.setText("Garantia: "+selecionadoObs.getUsuario_obs().getGarantia());
     jLabelGERENCIA.setText("Gerência: "+selecionadoObs.getUsuario_obs().getGerencia().getGerencia());
     jLabelHOST.setText(selecionadoObs.getUsuario_obs().getNomepc());
     jLabelMODELO_MICRO.setText("Modelo do Micro: "+selecionadoObs.getUsuario_obs().getModeloMicro().getModelo());
     jLabelMODELO_MONITOR.setText("modelo do Monitor: "+selecionadoObs.getUsuario_obs().getModeloMonitor().getModelo());
     jLabelPAVIMENTO.setText("Pavimento: "+selecionadoObs.getUsuario_obs().getPavimentoUsuario().getPavimento());
     jLabelPLATAFORMA.setText("Plataforma: "+selecionadoObs.getUsuario_obs().getPlataformaMicro().getPlataforma());
     jLabelSERIE_MICRO.setText("Série do Micro: "+selecionadoObs.getUsuario_obs().getSerieMicro());
     jLabelSERIE_MONITOR.setText("Série do Monitor: "+selecionadoObs.getUsuario_obs().getSerieMonitor());
     jLabelTOMBO_MICRO.setText("Tombamento do Micro: "+selecionadoObs.getUsuario_obs().getTombamentoMicro()+"");
     jLabelTOMBO_MONITOR.setText("Tombamento do Monitor: "+selecionadoObs.getUsuario_obs().getTombamentoMonitor()+"");
     
     TextAreaOBS.setText(selecionadoObs.getObs());
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaOBS = new javax.swing.JTextArea();
        ButtonAlterarObs = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelGERENCIA = new javax.swing.JLabel();
        jLabelTOMBO_MICRO = new javax.swing.JLabel();
        jLabelSERIE_MONITOR = new javax.swing.JLabel();
        jLabelTOMBO_MONITOR = new javax.swing.JLabel();
        jLabelMODELO_MICRO = new javax.swing.JLabel();
        jLabelMODELO_MONITOR = new javax.swing.JLabel();
        jLabelSERIE_MICRO = new javax.swing.JLabel();
        jLabelCONFIG = new javax.swing.JLabel();
        jLabelPLATAFORMA = new javax.swing.JLabel();
        jLabelGARANTIA = new javax.swing.JLabel();
        jLabelUSER = new javax.swing.JLabel();
        jLabelPAVIMENTO = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabelHOST = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TextAreaOBS.setColumns(20);
        TextAreaOBS.setRows(5);
        jScrollPane1.setViewportView(TextAreaOBS);

        ButtonAlterarObs.setText("Alterar observação");
        ButtonAlterarObs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAlterarObsActionPerformed(evt);
            }
        });

        jLabel1.setText("Altere a observação:");

        jLabel2.setText("Serão armazenados automaticamente a data, hora e nome do usuário que alterou a observação.");

        jButton1.setText("Limpar texto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelGERENCIA.setText("Gerência:");

        jLabelTOMBO_MICRO.setText("Tombamento do Micro:");

        jLabelSERIE_MONITOR.setText("Série do Monitor:");

        jLabelTOMBO_MONITOR.setText("Tombamento do Monitor:");

        jLabelMODELO_MICRO.setText("Modelo do Micro:");

        jLabelMODELO_MONITOR.setText("Modelo do Monitor:");

        jLabelSERIE_MICRO.setText("Série do Micro:");

        jLabelCONFIG.setText("Configuração:");

        jLabelPLATAFORMA.setText("Plataforma:");

        jLabelGARANTIA.setText("Garantia:");

        jLabelUSER.setText("Usuário:");

        jLabelPAVIMENTO.setText("Pavimento:");

        jLabel7.setText("Informações sobre o equipamento");

        jLabelHOST.setText("Host");

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Voltar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Sair do Sistema");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 342, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonAlterarObs))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTOMBO_MICRO)
                                    .addComponent(jLabelTOMBO_MONITOR)
                                    .addComponent(jLabelCONFIG)
                                    .addComponent(jLabelUSER))
                                .addGap(146, 146, 146)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSERIE_MONITOR)
                                    .addComponent(jLabelSERIE_MICRO)
                                    .addComponent(jLabelPLATAFORMA)
                                    .addComponent(jLabelPAVIMENTO))
                                .addGap(137, 137, 137)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMODELO_MICRO)
                                    .addComponent(jLabelMODELO_MONITOR)
                                    .addComponent(jLabelGARANTIA)
                                    .addComponent(jLabelGERENCIA))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelHOST)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabelHOST, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTOMBO_MICRO)
                            .addComponent(jLabelMODELO_MICRO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTOMBO_MONITOR)
                            .addComponent(jLabelMODELO_MONITOR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCONFIG)
                            .addComponent(jLabelGARANTIA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUSER)
                            .addComponent(jLabelGERENCIA)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSERIE_MICRO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSERIE_MONITOR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPLATAFORMA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPAVIMENTO)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonAlterarObs, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAlterarObsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAlterarObsActionPerformed
        try{

            Obs alterarObs = new Obs();
            alterarObs.setUsuario_obs(selecionadoObs.getUsuario_obs());

            alterarObs.setObs(TextAreaOBS.getText());

            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");
            Date date = new Date();
            String dataAlt;
            dataAlt = dateFormat.format(date);

            alterarObs.setData_obs(dataAlt);

            //String nomeUsuarioPC = System.getProperty("user.name");

            alterarObs.setNome_usuario(this.logado.getLogin());

            Fachada.getInstancia().alterarObservacao(alterarObs,this.selecionadoObs);

            JOptionPane.showMessageDialog(rootPane, "Observação alterada com sucesso!");

            dispose();

        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null,  "Erro ao alterar observação."+ex.getMessage());
        }
    }//GEN-LAST:event_ButtonAlterarObsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
dispose();      
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
 System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      TextAreaOBS.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObsAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObsAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObsAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObsAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObsAlterar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAlterarObs;
    private javax.swing.JTextArea TextAreaOBS;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCONFIG;
    private javax.swing.JLabel jLabelGARANTIA;
    private javax.swing.JLabel jLabelGERENCIA;
    private javax.swing.JLabel jLabelHOST;
    private javax.swing.JLabel jLabelMODELO_MICRO;
    private javax.swing.JLabel jLabelMODELO_MONITOR;
    private javax.swing.JLabel jLabelPAVIMENTO;
    private javax.swing.JLabel jLabelPLATAFORMA;
    private javax.swing.JLabel jLabelSERIE_MICRO;
    private javax.swing.JLabel jLabelSERIE_MONITOR;
    private javax.swing.JLabel jLabelTOMBO_MICRO;
    private javax.swing.JLabel jLabelTOMBO_MONITOR;
    private javax.swing.JLabel jLabelUSER;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
