/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiJP;

import java.awt.event.KeyEvent;

import javax.swing.JOptionPane;

import Login.LoginUser;
import Principal.TelaPrincipal;

/**
 *
 * @author joao.paulo
 */
public class TelaEquipamentosEscolha extends javax.swing.JFrame {

    /**
     * Creates new form EquipamentosEscolha
     */
    public TelaEquipamentosEscolha() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Equipamentos");

    }
    private LoginUser logado;

    public TelaEquipamentosEscolha(LoginUser logado) {
        // Tem que atualizar o user para usar quem estiver em sessão
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Equipamentos");

        this.logado = logado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonEquipHP = new javax.swing.JButton();
        jButtonFornHP = new javax.swing.JButton();
        jButtonNFHP = new javax.swing.JButton();
        jLabelAjuda = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel1.setText("O QUE VOCÊ DESEJA ACESSAR?");

        jButtonEquipHP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonEquipHP.setForeground(new java.awt.Color(204, 0, 0));
        jButtonEquipHP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/run_32.png"))); // NOI18N
        jButtonEquipHP.setText("Equipamento ");
        jButtonEquipHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEquipHPActionPerformed(evt);
            }
        });
        jButtonEquipHP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonEquipHPKeyPressed(evt);
            }
        });

        jButtonFornHP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonFornHP.setForeground(new java.awt.Color(204, 0, 0));
        jButtonFornHP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/run_32.png"))); // NOI18N
        jButtonFornHP.setText(" Fornecedor");
        jButtonFornHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFornHPActionPerformed(evt);
            }
        });

        jButtonNFHP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonNFHP.setForeground(new java.awt.Color(204, 0, 0));
        jButtonNFHP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/run_32.png"))); // NOI18N
        jButtonNFHP.setText(" Nota Fiscal ");
        jButtonNFHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNFHPActionPerformed(evt);
            }
        });

        jLabelAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/help_32.png"))); // NOI18N
        jLabelAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAjudaMouseClicked(evt);
            }
        });

        jLabel3.setText("Ajuda:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/arrow_left_32.png"))); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Atalhos");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Fornecedor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Equipamento");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("NotaFiscal");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAjuda)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFornHP, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEquipHP, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNFHP, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelAjuda))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFornHP, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNFHP, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEquipHP, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEquipHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEquipHPActionPerformed
        TelaConsultaEquip telaEquipHP = new TelaConsultaEquip(this.logado);
        telaEquipHP.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonEquipHPActionPerformed

    private void jButtonEquipHPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonEquipHPKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonEquipHP.doClick();
        }
    }//GEN-LAST:event_jButtonEquipHPKeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaConsultaForn telaFornHP = new TelaConsultaForn(this.logado);
        telaFornHP.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaConsultaEquip telaEquipHP = new TelaConsultaEquip(this.logado);
        telaEquipHP.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButtonFornHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFornHPActionPerformed
        TelaConsultaForn telaFornHP = new TelaConsultaForn(this.logado);
        telaFornHP.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonFornHPActionPerformed

    private void jButtonNFHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNFHPActionPerformed
        TelaConsultaNF tela = new TelaConsultaNF(this.logado);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonNFHPActionPerformed

    private void jLabelAjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAjudaMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Para realizar o cadastro da nota fiscal você deve:\n"
                + "1º Cadastrar o Fornecedor;\n"
                + "2º Cadastrar os Equipamentos daquele Fornecedor;\n"
                + "3º Cadastrar a Nota Fiscal daquele Fornecedor;\n"
                + "4º Adicionar os itens a Nota.");
    }//GEN-LAST:event_jLabelAjudaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       TelaPrincipal tela = new TelaPrincipal(this.logado);
       tela.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       TelaConsultaNF tela = new TelaConsultaNF(this.logado);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEquipamentosEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEquipamentosEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEquipamentosEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEquipamentosEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEquipamentosEscolha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEquipHP;
    private javax.swing.JButton jButtonFornHP;
    private javax.swing.JButton jButtonNFHP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAjuda;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
