/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiJP;

import java.awt.event.KeyEvent;
import java.util.ArrayList;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import ClassesBasicasJP.Equipamentos;
import ClassesBasicasJP.Fornecedor;
import Geral.Fachada;
import Login.LoginUser;

/**
 *
 * @author joao.paulo
 */
public class TelaConsultaEquip extends javax.swing.JFrame {

    /**
     * Creates new form TelaPasso1
     */
    public TelaConsultaEquip() {
        initComponents();
        setTitle("Equipamento ");
        setLocationRelativeTo(null);

    }
    private LoginUser logado = new LoginUser();


    public TelaConsultaEquip(LoginUser logado) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Equipamento ");
        this.logado = logado;

    }

    ArrayList<Equipamentos> listaEquip;
    ArrayList<Fornecedor> listaForn;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaEquipamentos = new javax.swing.JTable();
        jButtonConsultar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jComboBoxFiltrar = new javax.swing.JComboBox<>();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonIr = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("CONSULTAR EQUIPAMENTO");

        TabelaEquipamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Tombamento", "Número Série", "Categoria", "Especificação", "Valor Unitário", "Cnpj", "Fornecedor"
            }
        ));
        TabelaEquipamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaEquipamentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaEquipamentos);

        jButtonConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/sort_desccending.png"))); // NOI18N
        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jButtonAlterar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/import.png"))); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/reject_document.png"))); // NOI18N
        jButtonRemover.setText(" Remover");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/arrow_left_32.png"))); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Pesquisar:");

        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyPressed(evt);
            }
        });

        jComboBoxFiltrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o campo da pesquisa", "Código", "Tombamento", "Número Série", "Tipo", "Categoria", "Especificação", "Valor Unitário", "Cnpj", "Fornecedor" }));
        jComboBoxFiltrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxFiltrarKeyPressed(evt);
            }
        });

        jButtonCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/accept_document.png"))); // NOI18N
        jButtonCadastrar.setText("Novo");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonIr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/run_32.png"))); // NOI18N
        jButtonIr.setText("Ir");
        jButtonIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIrActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("OBS:");

        jLabel13.setText("Caso não seja selecionado um campo de pesquisa, a consulta");

        jLabel14.setText(" será feita em todos os campos da tabela abaixo.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jComboBoxFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonIr)
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 160, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jButtonAlterar)
                .addGap(82, 82, 82)
                .addComponent(jButtonRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVoltar)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(443, 443, 443))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonConsultar)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonIr)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAlterar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCadastrar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonRemover)
                                .addComponent(jButtonVoltar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        try {
       
                listaEquip = Fachada.getInstancia().listaTudoEquip();
                DefaultTableModel tabelaEquip = new DefaultTableModel() {
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                ;

                };
        tabelaEquip.setColumnIdentifiers(new String[]{"Código", "Tombamento", "Número Série", "Categoria", "Especificação", "Valor Unitário", "Cnpj", "Fornecedor"});
                for (Equipamentos equip : listaEquip) {
                    tabelaEquip.addRow(new String[]{Integer.toString(equip.getCodigo()), equip.getTombamento(), equip.getSerie(), equip.getCategoria(), equip.getEspecificacao(), equip.getValUnitario(),
                        equip.getCnpj_forn().getCnpj(), equip.getCnpj_forn().getNome()});

                    TabelaEquipamentos.setModel(tabelaEquip);
                    TabelaEquipamentos.getColumnModel().getColumn(0).setMaxWidth(50);
                    TabelaEquipamentos.getColumnModel().getColumn(1).setMaxWidth(150);
                    TabelaEquipamentos.getColumnModel().getColumn(2).setMaxWidth(100);
                    TabelaEquipamentos.getColumnModel().getColumn(3).setMaxWidth(150);
                    TabelaEquipamentos.getColumnModel().getColumn(4).setMaxWidth(260);
                    TabelaEquipamentos.getColumnModel().getColumn(5).setMaxWidth(120);
                    TabelaEquipamentos.getColumnModel().getColumn(6).setMaxWidth(150);
                    TabelaEquipamentos.getColumnModel().getColumn(7).setMaxWidth(390);
                }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        if (TabelaEquipamentos.getSelectedRow() >= 0) {
            Equipamentos selecionado;
            selecionado = listaEquip.get(TabelaEquipamentos.getSelectedRow());

            TelaAlterarEquip alterar = new TelaAlterarEquip(selecionado, this.logado);
            alterar.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione na tabela um Equipamento para ser alterado");

        }

        //ArrayList<Equipamentos> listaEquip;
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        if (TabelaEquipamentos.getSelectedRow() >= 0) {
            Equipamentos removeEquip;
            removeEquip = listaEquip.get(TabelaEquipamentos.getSelectedRow());
            if (JOptionPane.showConfirmDialog(new JFrame(),
                    "Tem certeza que deseja remover o(a) (" + removeEquip.getCategoria()+ ")? (Esta ação não poderá ser desfeita)",
                    "Remover este Equipamento", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try {
                    int selectRow = (TabelaEquipamentos.getSelectedRow());
                    Fachada.getInstancia().removerEquipamentos(removeEquip);
                    JOptionPane.showMessageDialog(rootPane, removeEquip.getCategoria() + " foi removido com sucesso");
                    listaEquip.remove(selectRow);
                    jButtonConsultar.doClick();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Operação cancelada.");
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione na tabela um Equipamento para ser removido");
        }
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaEquipamentosEscolha inicial = new TelaEquipamentosEscolha(this.logado);
        inicial.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void TabelaEquipamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaEquipamentosMouseClicked
        if (TabelaEquipamentos.getSelectedRow() >= 0) {
            Equipamentos selecionado;
            selecionado = listaEquip.get(TabelaEquipamentos.getSelectedRow());
        if (evt.getClickCount() > 1) {
            TelaNovoTombEquip tela = new TelaNovoTombEquip(selecionado);
             tela.setVisible(true);
             
        
        }
        }
        
        /*   Equipamentos equip = new Equipamentos();
         if (TabelaEquipamentos.getSelectedRow() >= 0) {
            Equipamentos selecionado;
            selecionado = listaEquip.get(TabelaEquipamentos.getSelectedRow());
        if (evt.getClickCount() > 1) {
            long tom = Long.parseLong(JOptionPane.showInputDialog("Informe o novo valor do tombamento: ").trim());
            equip.setTombamento(tom);
             try {
                    Fachada.getInstancia().alterarTombEquipamentos(equip, selecionado);
                    JOptionPane.showMessageDialog(rootPane, "Tombamento alterado com sucesso");
                    jButtonConsultar.doClick(WIDTH);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, "Erro - " + ex.getMessage());
                }
        }
        }*/
    }//GEN-LAST:event_TabelaEquipamentosMouseClicked

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        TelaNovoEquip novo = new TelaNovoEquip(this.logado);
        novo.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIrActionPerformed
        try {
            String filtroEquips = jTextFieldPesquisa.getText().trim();
            Object selecionadoPosicao = jComboBoxFiltrar.getSelectedItem();
            String selecionado = selecionadoPosicao.toString();

            listaEquip = Fachada.getInstancia().listaFiltroEquipamentos(filtroEquips, selecionado);
            DefaultTableModel tabelaEquip = new DefaultTableModel() {
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            ;

            };
             tabelaEquip.setColumnIdentifiers(new String[]{"Código", "Tombamento", "Número Série", "Categoria", "Especificação", "Valor Unitário", "Cnpj", "Fornecedor"});
                for (Equipamentos equip : listaEquip) {
                    tabelaEquip.addRow(new String[]{ Integer.toString(equip.getCodigo()), equip.getTombamento(), equip.getSerie(), equip.getCategoria(), equip.getEspecificacao(), equip.getValUnitario(),
                        equip.getCnpj_forn().getCnpj(), equip.getCnpj_forn().getNome()});

                    TabelaEquipamentos.setModel(tabelaEquip);
                    TabelaEquipamentos.getColumnModel().getColumn(0).setMaxWidth(50);
                    TabelaEquipamentos.getColumnModel().getColumn(1).setMaxWidth(150);
                    TabelaEquipamentos.getColumnModel().getColumn(2).setMaxWidth(100);
                    TabelaEquipamentos.getColumnModel().getColumn(3).setMaxWidth(150);
                    TabelaEquipamentos.getColumnModel().getColumn(4).setMaxWidth(260);
                    TabelaEquipamentos.getColumnModel().getColumn(5).setMaxWidth(120);
                    TabelaEquipamentos.getColumnModel().getColumn(6).setMaxWidth(150);
                    TabelaEquipamentos.getColumnModel().getColumn(7).setMaxWidth(390);
                }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonIrActionPerformed

    private void jTextFieldPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           jButtonIr.doClick();
       }
    }//GEN-LAST:event_jTextFieldPesquisaKeyPressed

    private void jComboBoxFiltrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxFiltrarKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           jButtonIr.doClick();
         }
    }//GEN-LAST:event_jComboBoxFiltrarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaEquip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaEquip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaEquip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaEquip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultaEquip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaEquipamentos;
    protected static javax.swing.JButton jButtonAlterar;
    protected static javax.swing.JButton jButtonCadastrar;
    protected static javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonIr;
    protected static javax.swing.JButton jButtonRemover;
    protected static javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxFiltrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
