/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiJP;

import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import ClassesBasicasJP.ItensDaNota;
import ClassesBasicasJP.NotaFiscal;
import Geral.Fachada;
import Login.LoginUser;

/**
 *
 * @author joao.paulo
 */
public class TelaDetalhesNF extends javax.swing.JFrame {

    /**
     * Creates new form TelaDetalhesNF
     */
    public TelaDetalhesNF() {
        initComponents();
        setTitle("Detalhes Da Nota");
        setLocationRelativeTo(null);
    }

    TelaDetalhesNF(NotaFiscal nf, LoginUser logado) {
        initComponents();
        setTitle("Detalhes Da Nota");
        setLocationRelativeTo(null);
        
        jLabelCodigo.setText(nf.getCodigo() + "");
        jLabelNotaFiscal.setText(nf.getNotaFiscal() + "");
        jLabelData.setText(nf.getData());
        jLabelFornecedor.setText(nf.getCod_Forn().getNome());
        this.nf = nf;

        jMenuItemConsultar.doClick(WIDTH);
    }
    ArrayList<ItensDaNota> listaItens;
    NotaFiscal nf;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaDetalhes = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelNotaFiscal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabelFornecedor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelValTotal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemConsultar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("DETALHES DA NOTA");

        TabelaDetalhes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Especificação", "Valor Unitário", "Quantidade", "Valor Total Item"
            }
        ));
        jScrollPane1.setViewportView(TabelaDetalhes);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Código:");

        jLabelCodigo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelCodigo.setForeground(new java.awt.Color(0, 0, 255));
        jLabelCodigo.setText("jLabel8");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nota Fiscal:");

        jLabelNotaFiscal.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelNotaFiscal.setForeground(new java.awt.Color(0, 0, 255));
        jLabelNotaFiscal.setText("jLabel8");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Data da Nota:");

        jLabelData.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(0, 0, 255));
        jLabelData.setText("jLabel8");

        jLabelFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFornecedor.setForeground(new java.awt.Color(0, 0, 255));
        jLabelFornecedor.setText("jLabel9");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Fornecedor:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/cross_32.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Valor Total da nota :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("R$");

        jLabelValTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelValTotal.setForeground(new java.awt.Color(0, 0, 255));
        jLabelValTotal.setText("0");

        jMenu1.setText("Atalho");

        jMenuItemConsultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemConsultar.setText("Consulta NF");
        jMenuItemConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemConsultar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelValTotal)
                .addGap(228, 228, 228)
                .addComponent(jButton2)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCodigo)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNotaFiscal)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelData))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelFornecedor))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCodigo)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabelNotaFiscal))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabelData)))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelFornecedor))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel4)
                        .addComponent(jLabelValTotal)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarActionPerformed
        try {
            int nf = Integer.parseInt(jLabelCodigo.getText());
            listaItens = Fachada.getInstancia().listaItensDaNota(nf);

            DefaultTableModel tabelaItensDaNota = new DefaultTableModel() {
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
                ;

            };

            tabelaItensDaNota.setColumnIdentifiers(new String[]{"Código", "Categoria", "Especificação", "Valor Unitário", "Quantidade", "Valor Total Item"});
            for (ItensDaNota itens : listaItens) {
                tabelaItensDaNota.addRow(new String[]{itens.getCodigo() + "", itens.getCod_Equip().getCategoria(), itens.getCod_Equip().getEspecificacao(), itens.getValorUnidade(), itens.getQuantidade() + "", itens.getValorTotalItem() + ""});

                TabelaDetalhes.setModel(tabelaItensDaNota);
                TabelaDetalhes.getColumnModel().getColumn(0).setMaxWidth(50);
                TabelaDetalhes.getColumnModel().getColumn(1).setMaxWidth(130);
                TabelaDetalhes.getColumnModel().getColumn(2).setMaxWidth(260);
                TabelaDetalhes.getColumnModel().getColumn(3).setMaxWidth(100);
                TabelaDetalhes.getColumnModel().getColumn(4).setMaxWidth(100);
                TabelaDetalhes.getColumnModel().getColumn(5).setMaxWidth(150);

            }
            if (tabelaItensDaNota.getRowCount() == 0) {
                tabelaItensDaNota.removeRow(nf);
            }

            //-------------------------VALOR TOTAL NOTA----------------------
            jLabelValTotal.setText("0");
            for (ItensDaNota itens : listaItens) {
                if(jLabelValTotal.getText().equals("0")){//SE FOR A PRIMEIRA INSERÇÃO
                    String valor0 = "0";

                    //PEGANDO O VALOR DA TABELA E CONCATENANDO O FORMATADO
                    String val1 = itens.getValorTotalItem().substring(0, itens.getValorTotalItem().length() - 3).replace(".", "");//TIRANDO OS . DO NUMERO E ADICIONANDO A VARIAVEL VAL1
                    String val2 = itens.getValorTotalItem().substring(itens.getValorTotalItem().length() - 3).replace(",", ".");//TRANSFORMANDO A , EM . E ADICIONANDO A VARIAVEL VAL2
                    String valFinal = val1 + val2;//CONCATENANDO AS VARIAVEIS VAL 1 E 2
                    BigDecimal bd1 = new BigDecimal(valFinal);//PEGANDO VALOR TOTAL DO ITEM(O RESULTADO CONCATENADO)
                    BigDecimal bd2 = new BigDecimal(valor0);//PEGANDO O SEGUNDO VALOR

                    //SOMANDO
                    BigDecimal valorFinal = bd1.add(bd2);//SOMANDO O VALOR UNITARIO  PELA QTD
                    NumberFormat numberValorTotal = NumberFormat.getNumberInstance();//DECLARANDO UMA VARIAVEL DO TIPO NUMBERFORMAT
                    String formatadoValorTotal = numberValorTotal .format(valorFinal);//FORMATANDO O RESULTADO COM .(MILHAR) E ,(DECIMAIS)
                    jLabelValTotal.setText(formatadoValorTotal);//SETANDO O RESULTADO DA SOMA FORMATADA NA JLABEL.

                }else{//SE JA HOUVER + INSERÇÕES PARA ALTERAR O VALOR JA EXISTENTE NA JLABEL

                    String valor0 = jLabelValTotal.getText();//PEGANDO O VALOR EXISTENTE DA JLABEL

                    //PEGANDO O VALOR DA TABELA E CONCATENANDO O FORMATADO
                    String val1 = itens.getValorTotalItem().substring(0, itens.getValorTotalItem().length() - 3).replace(".", "");//TIRANDO OS . DO NUMERO E ADICIONANDO A VARIAVEL VAL1
                    String val2 = itens.getValorTotalItem().substring(itens.getValorTotalItem().length() - 3).replace(",", ".");//TRANSFORMANDO A , EM . E ADICIONANDO A VARIAVEL VAL2
                    String valFinal = val1 + val2;//CONCATENANDO AS VARIAVEIS VAL 1 E 2
                    BigDecimal bd1 = new BigDecimal(valFinal);//PEGANDO VALOR TOTAL DO ITEM(O RESULTADO CONCATENADO)

                    //PEGANDO O VALOR EXISTENTE NO jLABEL E CONCATENANDO O FORMATADO
                    String val3 = valor0.substring(0, itens.getValorTotalItem().length() - 3).replace(".", "");//TIRANDO OS . DO NUMERO E ADICIONANDO A VARIAVEL VAL1
                    String val4 = valor0.substring(itens.getValorTotalItem().length() - 3).replace(",", ".");//TRANSFORMANDO A , EM . E ADICIONANDO A VARIAVEL VAL2
                    String valorFinal2 = val3 + val4;//CONCATENANDO AS VARIAVEIS VAL 3 E 4
                    BigDecimal bd2 = new BigDecimal(valorFinal2);//PEGANDO O SEGUNDO VALOR

                    //SOMANDO
                    BigDecimal valorFinal = bd1.add(bd2);//SOMANDO O VALOR UNITARIO  PELA QTD
                    NumberFormat numberValorTotal = NumberFormat.getNumberInstance();//DECLARANDO UMA VARIAVEL DO TIPO NUMBERFORMAT
                    String formatadoValorTotal = numberValorTotal .format(valorFinal);//FORMATANDO O RESULTADO COM .(MILHAR) E ,(DECIMAIS)
                    jLabelValTotal.setText(formatadoValorTotal);//SETANDO O RESULTADO DA SOMA FORMATADA NA JLABEL.

                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro - " + ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItemConsultarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDetalhesNF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDetalhesNF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDetalhesNF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDetalhesNF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDetalhesNF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaDetalhes;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelFornecedor;
    private javax.swing.JLabel jLabelNotaFiscal;
    private javax.swing.JLabel jLabelValTotal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemConsultar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
