/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiJP;

import static GuiJP.TelaConsultaForn.jButtonAlterar;
import static GuiJP.TelaConsultaForn.jButtonCadastrar;
import static GuiJP.TelaConsultaForn.jButtonConsultar;
import static GuiJP.TelaConsultaForn.jButtonRemover;
import static GuiJP.TelaConsultaForn.jButtonVoltar;

import java.awt.event.KeyEvent;

import javax.swing.JOptionPane;

import ClassesBasicasJP.Fornecedor;
import Geral.Fachada;
import Login.LoginUser;

/**
 *
 * @author joao.paulo
 */
public class TelaAlterarForn extends javax.swing.JFrame {

    private LoginUser logado;
    private Fornecedor selecionado;

    public TelaAlterarForn() {
        initComponents();
        setTitle("Formulário de a alteração dos Fornecedores.");
        setLocationRelativeTo(null);

    }

    public TelaAlterarForn(Fornecedor selecionado) {
        initComponents();
        setLocationRelativeTo(null);

    }

    TelaAlterarForn(Fornecedor selecionado, LoginUser logado) {
        initComponents();
        setTitle("Formulário de a alteração dos Fornecedores.");
        setLocationRelativeTo(null);
        this.logado = logado;

        //CARREGANDO DADOS DO EQUIPAMENTO QUE DESEJA SER ALTERADO
        jLabelCnpj.setText(selecionado.getCnpj());
        jTextFieldForn.setText(selecionado.getNome());

        this.selecionado = selecionado;

//        jButtonCadastrar.setEnabled(false);
        jButtonConsultar.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonRemover.setEnabled(false);
        jButtonVoltar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelCnpj = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldForn = new javax.swing.JTextField();
        jToggleButtonAlt = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setText("ALTERAR FORNECEDOR");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Cnpj:");

        jLabelCnpj.setText("jLabel3");

        jLabel4.setText("Fornecedor:");

        jTextFieldForn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldFornKeyPressed(evt);
            }
        });

        jToggleButtonAlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/diskette_32.png"))); // NOI18N
        jToggleButtonAlt.setText("Alterar");
        jToggleButtonAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAltActionPerformed(evt);
            }
        });

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/arrow_left_32.png"))); // NOI18N
        jToggleButton2.setText("Voltar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButtonAlt)
                        .addGap(212, 212, 212)
                        .addComponent(jToggleButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldForn, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelCnpj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAltActionPerformed
        try {
            Fornecedor alterFornecedor = new Fornecedor();

            alterFornecedor.setCnpj(jLabelCnpj.getText().trim().toUpperCase());
            alterFornecedor.setNome(jTextFieldForn.getText().trim().toUpperCase());

            Fachada.getInstancia().alterarFornecedor(alterFornecedor, selecionado);
            JOptionPane.showMessageDialog(rootPane, "Equipamento : " + alterFornecedor.getNome() + " alterado com sucesso.");

            jButtonCadastrar.setEnabled(true);
            jButtonConsultar.setEnabled(true);
            jButtonConsultar.doClick();
            jButtonAlterar.setEnabled(true);
            jButtonRemover.setEnabled(true);
            jButtonVoltar.setEnabled(true);

            dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }


    }//GEN-LAST:event_jToggleButtonAltActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        jButtonConsultar.setEnabled(true);
        jButtonConsultar.doClick();
        jButtonAlterar.setEnabled(true);
        jButtonRemover.setEnabled(true);
        jButtonVoltar.setEnabled(true);
        dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jTextFieldFornKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFornKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           jToggleButtonAlt.doClick();
       }
    }//GEN-LAST:event_jTextFieldFornKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarForn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarForn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarForn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarForn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlterarForn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCnpj;
    private javax.swing.JTextField jTextFieldForn;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButtonAlt;
    // End of variables declaration//GEN-END:variables
}
