/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiJP;

import static GuiJP.TelaConsultaNF.jButtonADD;
import static GuiJP.TelaConsultaNF.jButtonAlterar;
import static GuiJP.TelaConsultaNF.jButtonCadastrar;
import static GuiJP.TelaConsultaNF.jButtonConsultar;
import static GuiJP.TelaConsultaNF.jButtonRemover;
import static GuiJP.TelaConsultaNF.jButtonVoltar;

import java.awt.event.KeyEvent;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import ClassesBasicasJP.Fornecedor;
import ClassesBasicasJP.NotaFiscal;
import Geral.Fachada;
import Login.LoginUser;

/**
 *
 * @author joao.paulo
 */
public class TelaAlterarNF extends javax.swing.JFrame {

    /**
     * Creates new form TelaAlterarNF
     */
    
    private LoginUser logado;
    private NotaFiscal selecionado;
    ArrayList<Fornecedor> listaForn;
    
    public TelaAlterarNF() {
        initComponents();
        setTitle("Atualzar Nota");
        setLocationRelativeTo(null);
    }

    TelaAlterarNF(NotaFiscal selecionado, LoginUser logado) {
        initComponents();
        setTitle("Atualzar Nota");
        setLocationRelativeTo(null);
        //RECEBENDO DADOS E SETANDO NOS TEXTOS
        jTextFieldNotaFiscal.setText(selecionado.getNotaFiscal() + "");
        jTextFieldData.setText(selecionado.getData());
        jTextFieldCnpj.setText(selecionado.getCod_Forn().getCnpj());
        jTextFieldCnpj.setEnabled(false);
        jTextFieldFornecedor.setText(selecionado.getCod_Forn().getNome());
        jTextFieldFornecedor.setEnabled(false);
        
        this.selecionado = selecionado;
        
        jButtonConsultar.setEnabled(false);
        jButtonCadastrar.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonRemover.setEnabled(false);
        jButtonVoltar.setEnabled(false);
        jButtonADD.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNotaFiscal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");
            jTextFieldData = new javax.swing.JFormattedTextField(data);
        }catch(Exception ex){

        }
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaFornecedor = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCnpj = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldFornecedor = new javax.swing.JTextField();
        jButtonAltConsultar = new javax.swing.JButton();
        jButtonAlterar1 = new javax.swing.JButton();
        jButtonAltVoltar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabelAjuda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setText("ALTERAR NOTA FISCAL");

        jTextFieldNotaFiscal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNotaFiscalKeyPressed(evt);
            }
        });

        jLabel2.setText("Nota Fiscal:");

        jLabel3.setText("Data da Nota:");

        jTextFieldData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDataKeyPressed(evt);
            }
        });

        TabelaFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cnpj", "Fornecedor"
            }
        ));
        jScrollPane1.setViewportView(TabelaFornecedor);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Cnpj:");

        jTextFieldCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCnpjKeyPressed(evt);
            }
        });

        jLabel5.setText("Fornecedor:");

        jTextFieldFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFornecedorActionPerformed(evt);
            }
        });
        jTextFieldFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldFornecedorKeyPressed(evt);
            }
        });

        jButtonAltConsultar.setText("Consultar");
        jButtonAltConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltConsultarActionPerformed(evt);
            }
        });

        jButtonAlterar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/diskette_32.png"))); // NOI18N
        jButtonAlterar1.setText("Alterar");
        jButtonAlterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterar1ActionPerformed(evt);
            }
        });

        jButtonAltVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/arrow_left_32.png"))); // NOI18N
        jButtonAltVoltar.setText("Voltar");
        jButtonAltVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltVoltarActionPerformed(evt);
            }
        });

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/format_painter.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jLabel6.setText("Ajuda:");

        jLabelAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/help_32.png"))); // NOI18N
        jLabelAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAjudaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButtonAlterar1)
                .addGap(71, 71, 71)
                .addComponent(jButtonLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAltVoltar)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(221, 221, 221)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabelAjuda)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAltConsultar)
                        .addContainerGap(324, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabelAjuda))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextFieldNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAltConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAltVoltar)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonAlterar1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFornecedorActionPerformed
       
    }//GEN-LAST:event_jTextFieldFornecedorActionPerformed

    private void jButtonAlterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterar1ActionPerformed
         NotaFiscal alterNF = new NotaFiscal();
            //TRATANDO CAMPO NOTA FISCAL
         try{
            try {
                alterNF.setNotaFiscal(Long.parseLong(jTextFieldNotaFiscal.getText().trim()));
            } catch (NumberFormatException ee) {
                if (jTextFieldNotaFiscal.getText().trim().equals("") == true) {
                    throw new Exception("O campo Nota Fiscal não pode ser vazio");
                } else {
                    throw new Exception("Preencha o campo Nota Fiscal apenas com numeros ");
                }
            }

            //RECEBENDO DADOS DOS OUTROS CAMPOS
            alterNF.setCodigo(selecionado.getCodigo());
            alterNF.setData(jTextFieldData.getText().trim().toUpperCase());

            //RECEBENDO VALOR ESCOLHIDO DO TIPO FORNECEDOR 
            if(TabelaFornecedor.getSelectedRow() >=0){
             Fornecedor escolhido = listaForn.get(TabelaFornecedor.getSelectedRow());
                alterNF.setCod_Forn(escolhido);
            } else{
                    alterNF.setCod_Forn(selecionado.getCod_Forn());
                
            }
            Fachada.getInstancia().AlterarNF(alterNF, selecionado);
            JOptionPane.showMessageDialog(rootPane, "A Nota Fiscal foi alterada com sucesso.");

            jButtonCadastrar.setEnabled(true);
            jButtonConsultar.setEnabled(true);
            jButtonAlterar.setEnabled(true);
            jButtonRemover.setEnabled(true);
            jButtonVoltar.setEnabled(true);
            jButtonADD.setEnabled(true);
            jButtonConsultar.doClick();
            dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }

    }//GEN-LAST:event_jButtonAlterar1ActionPerformed

    private void jButtonAltConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltConsultarActionPerformed
        try {

            listaForn = Fachada.getInstancia().listaEscolherForn();
            DefaultTableModel tabelaFornecedor = new DefaultTableModel() {
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            ;

            };

            tabelaFornecedor.setColumnIdentifiers(new String[]{"Cnpj", "Fornecedor"});
            TabelaFornecedor.getColumnModel().getColumn(0).setMaxWidth(160);
            TabelaFornecedor.getColumnModel().getColumn(1).setMaxWidth(380);

            for (Fornecedor forn : listaForn) {

                tabelaFornecedor.addRow(new String[]{forn.getCnpj(), forn.getNome()});

                TabelaFornecedor.setModel(tabelaFornecedor);
                TabelaFornecedor.getColumnModel().getColumn(0).setMaxWidth(160);
                TabelaFornecedor.getColumnModel().getColumn(1).setMaxWidth(380);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonAltConsultarActionPerformed

    private void jLabelAjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAjudaMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Para Alterar a nota você deve:\n"
                + "- Inserir os novos dados que deseja alterar nos seus devidos campos;\n"
                + "- Caso queira alterar o fornecedor: clique no botão consultar e Selecione o fornecedor da tabela;\n"
                + "- Clique em alterar para concluir ");
    }//GEN-LAST:event_jLabelAjudaMouseClicked

    private void jButtonAltVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltVoltarActionPerformed
        TelaConsultaNF tela = new TelaConsultaNF(this.logado);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAltVoltarActionPerformed

    private void jTextFieldNotaFiscalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNotaFiscalKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           jButtonAlterar1.doClick();
       }
    }//GEN-LAST:event_jTextFieldNotaFiscalKeyPressed

    private void jTextFieldDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDataKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           jButtonAlterar1.doClick();
       }
    }//GEN-LAST:event_jTextFieldDataKeyPressed

    private void jTextFieldCnpjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCnpjKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           jButtonAlterar1.doClick();
       }
    }//GEN-LAST:event_jTextFieldCnpjKeyPressed

    private void jTextFieldFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFornecedorKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           jButtonAlterar1.doClick();
       }
    }//GEN-LAST:event_jTextFieldFornecedorKeyPressed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
       jTextFieldNotaFiscal.setText("");
       jTextFieldData.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarNF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarNF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarNF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarNF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlterarNF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaFornecedor;
    private javax.swing.JButton jButtonAltConsultar;
    private javax.swing.JButton jButtonAltVoltar;
    private javax.swing.JButton jButtonAlterar1;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAjuda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCnpj;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldFornecedor;
    private javax.swing.JTextField jTextFieldNotaFiscal;
    // End of variables declaration//GEN-END:variables
}
