/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiJP;

import static GuiJP.TelaConsultaEquip.jButtonAlterar;
import static GuiJP.TelaConsultaEquip.jButtonCadastrar;
import static GuiJP.TelaConsultaEquip.jButtonConsultar;
import static GuiJP.TelaConsultaEquip.jButtonRemover;
import static GuiJP.TelaConsultaEquip.jButtonVoltar;

import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import ClassesBasicasJP.Equipamentos;
import ClassesBasicasJP.Fornecedor;
import Geral.Fachada;
import Login.LoginUser;

/**
 *
 * @author joao.paulo
 */
public class TelaAlterarEquip extends javax.swing.JFrame {

    /**
     * Creates new form TelaAlterarEquip
     */
    private LoginUser logado;
    private Equipamentos selecionado;

    ArrayList<Fornecedor> listaForn;

    public TelaAlterarEquip() {
        initComponents();
        setTitle("Formulário de a alteração dos Equipamentos.");
        setLocationRelativeTo(null);

    }

    public TelaAlterarEquip(Equipamentos selecionado) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Formulário de a alteração dos Equipamentos.");

    }

    public TelaAlterarEquip(Equipamentos selecionado, LoginUser logado) {
        initComponents();
        setTitle("Formulário de a alteração dos Equipamentos .");
        setLocationRelativeTo(null);
        this.logado = logado;

        //CARREGANDO DADOS DO EQUIPAMENTO QUE DESEJA SER ALTERADO
        jTextFieldOutraCateg.setText(selecionado.getCategoria());
        jTextFieldAltTomb.setText(selecionado.getTombamento().substring(7, 13));
        jTextFieldAltNumSerie.setText(selecionado.getSerie());
        jTextFieldAltEspecificacao.setText(selecionado.getEspecificacao());
        jTextFieldAltValUnit.setText(selecionado.getValUnitario().replace(",", "."));
        jTextFieldEscolherNomeForn.setText(selecionado.getCnpj_forn().getNome());
        //TRATANDO ESCOLHER FORNECEDOR
        jTextFieldEscolherCnpjForn.setEnabled(false);
        jTextFieldEscolherCnpjForn.setText(selecionado.getCnpj_forn().getCnpj());
        jTextFieldEscolherNomeForn.setEnabled(false);
        jTextFieldEscolherNomeForn.setText(selecionado.getCnpj_forn().getNome());

        this.selecionado = selecionado;

        jButtonCadastrar.setEnabled(false);
        jButtonConsultar.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonRemover.setEnabled(false);
        jButtonVoltar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextFieldAltEspecificacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAltValUnit = new javax.swing.JTextField();
        jButtonAlt1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        jTextFieldAltTomb = new javax.swing.JTextField();
        jTextFieldOutraCateg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaFornecedor = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEscolherCnpjForn = new javax.swing.JTextField();
        jTextFieldEscolherNomeForn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelAjuda = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelTomb1 = new javax.swing.JLabel();
        jComboBoxTomb3 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldAltNumSerie = new javax.swing.JTextField();

        textField1.setText("textField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Categoria:");

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tipo do equipamento", "BGR", "BRG", "CPU", "ESTABILIZADOR", "IMPRESSORA", "MICRO", "MONITOR", "MOUSE", "NO BREAK", "NOTEBOOK", "PEN DRIVE", "SCANNER", "SWITCH", "TECLADO", "OUTRO" }));
        jComboBoxCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCategoriaItemStateChanged(evt);
            }
        });

        jLabel5.setText("Especificação:");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/format_painter.png"))); // NOI18N
        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextFieldAltEspecificacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAltEspecificacaoKeyPressed(evt);
            }
        });

        jLabel3.setText("Valor Unitário:");

        jTextFieldAltValUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAltValUnitKeyPressed(evt);
            }
        });

        jButtonAlt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/diskette_32.png"))); // NOI18N
        jButtonAlt1.setText("Alterar");
        jButtonAlt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlt1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/arrow_left_32.png"))); // NOI18N
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setText("Alterar Equipamento");

        jLabel.setText("Tombamento:");

        jTextFieldAltTomb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAltTombKeyPressed(evt);
            }
        });

        jTextFieldOutraCateg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldOutraCategKeyPressed(evt);
            }
        });

        TabelaFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cnpj", "Fornecedor"
            }
        ));
        jScrollPane1.setViewportView(TabelaFornecedor);

        jButton5.setText("Consultar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Cnpj:");

        jTextFieldEscolherCnpjForn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEscolherCnpjFornKeyPressed(evt);
            }
        });

        jTextFieldEscolherNomeForn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEscolherNomeFornKeyPressed(evt);
            }
        });

        jLabel6.setText("Fornecedor:");

        jLabel7.setText("ajuda:");

        jLabelAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/help_32.png"))); // NOI18N
        jLabelAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAjudaMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("Ex: 1234567.89");

        jLabelTomb1.setText("120101.");

        jComboBoxTomb3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".2016", ".2017", ".2018", ".2019", ".2020", ".2021", ".2022", ".2023", ".2024", ".2025" }));
        
        jLabel9.setText("Número Série:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(jLabel1)
                        .addGap(301, 301, 301)
                        .addComponent(jLabel7)
                        .addGap(16, 16, 16)
                        .addComponent(jLabelAjuda))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButtonAlt1)
                        .addGap(49, 49, 49)
                        .addComponent(jButton3)
                        .addGap(605, 605, 605)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldOutraCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabelTomb1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldAltTomb, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxTomb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel2)))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAltEspecificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldAltValUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel8))
                                            .addComponent(jTextFieldEscolherCnpjForn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(27, 27, 27)
                                .addComponent(jTextFieldEscolherNomeForn, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldAltNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jButton5)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabelAjuda)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton5)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel)
                                    .addComponent(jLabelTomb1)
                                    .addComponent(jTextFieldAltTomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxTomb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addComponent(jTextFieldOutraCateg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldAltNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldAltEspecificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldAltValUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldEscolherCnpjForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6))
                            .addComponent(jTextFieldEscolherNomeForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAlt1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlt1ActionPerformed
        try {
            Equipamentos alterEquip = new Equipamentos();

            //TRATANDO CAMPO TOMBAMENTO
            if (jTextFieldAltTomb.getText().matches("[a-zA-Z]*")) {
                throw new Exception("Informe somente números no campo Tombamento");
            } else {
                Object selecionetombo = jComboBoxTomb3.getSelectedItem();
                alterEquip.setTombamento(jLabelTomb1.getText() + jTextFieldAltTomb.getText().trim() + selecionetombo.toString().trim());
            }

//---------------BACKUP ANTIGO TOMBAMENTO FUNCIONANDO                            
                            /* try {
             alterEquip.setTombamento(jTextFieldAltTomb.getText().trim());
             } catch (NumberFormatException ee) {
             if (jTextFieldAltTomb.getText().trim().equals("") == true) {
             throw new Exception("O campo Tombamento não pode ser vazio");
             } else {
             throw new Exception("Preencha o campo Tombamento apenas com numeros ");
             }
             }*/
            //TRATANDO COMBOBOX:    
            if (jComboBoxCategoria.getSelectedItem().equals("OUTRO") || jComboBoxCategoria.getSelectedItem().equals("Selecione o tipo do equipamento")) {
                if (jTextFieldOutraCateg.getText().trim().equals("") || jTextFieldOutraCateg.getText() == null) {
                    throw new Exception("Ao selecionar OUTRO, preencha o campo ao lado informando qual a categoria do equipamento");
                } else {
                    alterEquip.setCategoria(jTextFieldOutraCateg.getText().trim().toUpperCase());
                }
            } else {
                Object selecionetipo = jComboBoxCategoria.getSelectedItem();
                alterEquip.setCategoria(selecionetipo.toString().trim());
            }

            /*if (!jComboBoxCategoria.getSelectedItem().equals("OUTRO") || !jComboBoxCategoria.getSelectedItem().equals("Selecione o tipo do equipamento")) {
             Object selecionetipo = jComboBoxCategoria.getSelectedItem();
             alterEquip.setCategoria(selecionetipo.toString().trim());
             } else {
             if (jTextFieldOutraCateg.getText().trim().equals("") || jTextFieldOutraCateg.getText() == null) {
             throw new Exception("Ao selecionar OUTRO, preencha o campo ao lado informando qual a categoria do equipamento");
             } else {
             alterEquip.setCategoria(jTextFieldOutraCateg.getText().trim().toUpperCase());
             }
             }*/
            //TRATANDO CAMPO VALOR UNITÁRIO:
            if (jTextFieldAltValUnit.getText() == null || jTextFieldAltValUnit.getText().trim().equals("")) {
                throw new Exception("Informe o valor do equipamento no campo Valor Unitario");

            } else if (jTextFieldAltValUnit.getText().matches("[a-zA-Z]*")) {
                throw new Exception("Informe somente números no campo Valor Unitário");

            } else if (jTextFieldAltValUnit.getText().matches("[0-9]*\\.[0-9]*")) {

                String recebendo = jTextFieldAltValUnit.getText().replace(",", ".");
                BigDecimal valor = new BigDecimal(recebendo);
                NumberFormat nf = NumberFormat.getNumberInstance();
                String formatado = nf.format(valor);
                alterEquip.setValUnitario(formatado);

            } else {
                throw new Exception("Informe somente números e ponto para as casas decimais no campo Valor Unitário(EX: 12345.98) ");
            }

            //RECEBENDO DADOS DOS OUTROS CAMPOS
            alterEquip.setEspecificacao(jTextFieldAltEspecificacao.getText().trim().toUpperCase());

            //RECEBENDO NUMERO DE SERIE
            alterEquip.setSerie(jTextFieldAltNumSerie.getText().trim().toUpperCase());

            //RECEBENDO VALOR ESCOLHIDO DO TIPO FORNECEDOR 
            if (TabelaFornecedor.getSelectedRow() >= 0) {
                Fornecedor escolhido = listaForn.get(TabelaFornecedor.getSelectedRow());
                alterEquip.setCnpj_forn(escolhido);
            } else {
                alterEquip.setCnpj_forn(selecionado.getCnpj_forn());

            }
            Fachada.getInstancia().alterarEquipamentos(alterEquip, selecionado);
            JOptionPane.showMessageDialog(rootPane, "Equipamento : " + alterEquip.getEspecificacao() + " alterado com sucesso.");

            jButtonCadastrar.setEnabled(true);
            jButtonConsultar.setEnabled(true);
            jButtonConsultar.doClick();
            jButtonAlterar.setEnabled(true);
            jButtonRemover.setEnabled(true);
            jButtonVoltar.setEnabled(true);
            dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonAlt1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextFieldAltEspecificacao.setText("");
        jTextFieldAltValUnit.setText("");
        jTextFieldAltTomb.setText("0");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButtonCadastrar.setEnabled(true);
        jButtonConsultar.setEnabled(true);
        jButtonConsultar.doClick();
        jButtonAlterar.setEnabled(true);
        jButtonRemover.setEnabled(true);
//        jButtonPasso2.setEnabled(true);
        jButtonVoltar.setEnabled(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {

            listaForn = Fachada.getInstancia().listaEscolherForn();
            DefaultTableModel tabelaFornecedor = new DefaultTableModel() {
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            ;

            };

            tabelaFornecedor.setColumnIdentifiers(new String[]{"Cnpj", "Fornecedor"});
            TabelaFornecedor.getColumnModel().getColumn(0).setMaxWidth(160);
            TabelaFornecedor.getColumnModel().getColumn(1).setMaxWidth(380);

            for (Fornecedor forn : listaForn) {

                tabelaFornecedor.addRow(new String[]{forn.getCnpj(), forn.getNome()});

                TabelaFornecedor.setModel(tabelaFornecedor);
                TabelaFornecedor.getColumnModel().getColumn(0).setMaxWidth(160);
                TabelaFornecedor.getColumnModel().getColumn(1).setMaxWidth(380);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBoxCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaItemStateChanged
        if (jComboBoxCategoria.getSelectedItem().equals("OUTRO")) {
            jTextFieldOutraCateg.setText("");
            jTextFieldOutraCateg.setEnabled(true);
            jTextFieldOutraCateg.requestFocus();

        } else {
            jTextFieldOutraCateg.setText(selecionado.getCategoria());
            jTextFieldOutraCateg.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxCategoriaItemStateChanged

    private void jLabelAjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAjudaMouseClicked

        JOptionPane.showMessageDialog(rootPane, "Para Alterar o equipamento você deve:\n"
                + "- Inserir os novos dados que deseja alterar nos seus devidos campos;\n"
                + "- Caso queira alterar a categoria: Escolher uma opção de categoria(caso não tenha a opção, selecione OUTRO e informe no campo a categoria);\n"
                + "- Caso queira alterar o fornecedor: clique no botão consultar e Selecione o fornecedor da tabela;\n"
                + "- Clique em alterar para concluir ");


    }//GEN-LAST:event_jLabelAjudaMouseClicked

    private void jTextFieldOutraCategKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldOutraCategKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonAlt1.doClick();
        }
    }//GEN-LAST:event_jTextFieldOutraCategKeyPressed

    private void jTextFieldAltTombKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAltTombKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonAlt1.doClick();
        }
    }//GEN-LAST:event_jTextFieldAltTombKeyPressed

    private void jTextFieldAltEspecificacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAltEspecificacaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonAlt1.doClick();
        }
    }//GEN-LAST:event_jTextFieldAltEspecificacaoKeyPressed

    private void jTextFieldAltValUnitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAltValUnitKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonAlt1.doClick();
        }
    }//GEN-LAST:event_jTextFieldAltValUnitKeyPressed

    private void jTextFieldEscolherCnpjFornKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEscolherCnpjFornKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonAlt1.doClick();
        }
    }//GEN-LAST:event_jTextFieldEscolherCnpjFornKeyPressed

    private void jTextFieldEscolherNomeFornKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEscolherNomeFornKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonAlt1.doClick();
        }
    }//GEN-LAST:event_jTextFieldEscolherNomeFornKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaEquip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaEquip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaEquip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaEquip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlterarEquip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaFornecedor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAlt1;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxTomb3;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAjuda;
    private javax.swing.JLabel jLabelTomb1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAltEspecificacao;
    private javax.swing.JTextField jTextFieldAltNumSerie;
    private javax.swing.JTextField jTextFieldAltTomb;
    private javax.swing.JTextField jTextFieldAltValUnit;
    private javax.swing.JTextField jTextFieldEscolherCnpjForn;
    private javax.swing.JTextField jTextFieldEscolherNomeForn;
    private javax.swing.JTextField jTextFieldOutraCateg;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
