/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RelatoriosSAD;

import SADpe.Pavimento.Pavimento;
import com.cete.dynamicpdf.Document;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.Method;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.plaf.FileChooserUI;

/**
 *
 * @author airton.oliveira
 */
public class JanelaSalvar extends javax.swing.JFrame {

    /**
     * Creates new form JanelaSalvar
     */
    public JanelaSalvar() {
        initComponents();
    }

    
     final void icone() {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("src\\resources\\favicon-cor.png"));
            this.setIconImage(img);
        } catch (IOException e) {
        }
    }
    
    private Document documento;


    public JanelaSalvar(Document documento, Pavimento filtroPavimento) {
        icone();
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Salvar Relatório em PDF");
        this.documento = documento;

        String defaultFile="";
        Date data = new Date();
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            String dataString;
            dataString = dateFormat.format(data);  
            
        if(filtroPavimento.getPavimento().equals("")){
            
        defaultFile = "Relatório Equipamentos SAD - Completo - "+dataString;      
            
        }else{
            
        defaultFile = "Relatório Equipamentos SAD - "+filtroPavimento.getPavimento()+" - "+dataString;  
        
        } 
        

        try {
            
            FileChooserUI fcUi = janelaSalvarArquivo.getUI();
            Class<? extends FileChooserUI> fcClass = fcUi.getClass();
            Method setFileName = fcClass.getMethod("setFileName", String.class);
            setFileName.invoke(fcUi, defaultFile);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro - " + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        janelaSalvarArquivo = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        janelaSalvarArquivo.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        janelaSalvarArquivo.setApproveButtonToolTipText("");
        janelaSalvarArquivo.setDialogTitle("Salvar Relatório");
        janelaSalvarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                janelaSalvarArquivoActionPerformed(evt);
            }
        });
        janelaSalvarArquivo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                janelaSalvarArquivoPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(janelaSalvarArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(janelaSalvarArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void janelaSalvarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_janelaSalvarArquivoActionPerformed
        try {

            //JFileChooser input = new JFileChooser();
            //int result = input.showSaveDialog(this);
            String nomeDoArquivo;
            nomeDoArquivo = janelaSalvarArquivo.getSelectedFile() + ".pdf";

            if (!nomeDoArquivo.equals("null.pdf")) {

                this.documento.draw(nomeDoArquivo);
                JOptionPane.showMessageDialog(rootPane, "Relatório gerado com sucesso em:   \n" + "\"" + nomeDoArquivo + "\"");
                dispose();

            } else if (nomeDoArquivo.equals("null.pdf")) {

                dispose();

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro - " + e.getMessage());
        }
    }//GEN-LAST:event_janelaSalvarArquivoActionPerformed

    private void janelaSalvarArquivoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_janelaSalvarArquivoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_janelaSalvarArquivoPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaSalvar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaSalvar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaSalvar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaSalvar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaSalvar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser janelaSalvarArquivo;
    // End of variables declaration//GEN-END:variables
}
