/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Versao_Office;

import Micro.Configuracao.*;
import Geral.Fachada;
import Login.LoginUser;
import Principal.TelaPrincipal;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Posseidon
 */
public class ListarVersaoOffice extends javax.swing.JFrame {

    /**
     * Creates new form ListarConfig
     */
    public ListarVersaoOffice() {
        initComponents();
        setTitle("Listagem de Versões do Pacote Office");
        setLocationRelativeTo(null);
        jButtonListar.doClick();
    }
    
    private LoginUser logado;
    public ListarVersaoOffice(LoginUser logado) {
        initComponents();
        setTitle("Listagem de Versões do Pacote Office");
        setLocationRelativeTo(null);
        this.logado=logado;
        jButtonListar.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TodosOffice = new javax.swing.JTable();
        campoListar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonListar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jButtonCadastrarNova = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TodosOffice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Descrição do Pacote Office"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TodosOffice.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TodosOffice);

        campoListar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoListarKeyPressed(evt);
            }
        });

        jLabel1.setText("Descrição do Pacote Office:");

        jButtonListar.setText("Listar");
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonRemover.setText("Remover");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonCadastrarNova.setText("Cadastrar Novo Office");
        jButtonCadastrarNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarNovaActionPerformed(evt);
            }
        });

        jMenu1.setText("Arquivo");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCadastrarNova)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoListar, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonListar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoListar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCadastrarNova, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
 
  
    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
      if (TodosOffice.getSelectedRow() >= 0){
            VersaoOffice selecionadoVersaoOffice = new VersaoOffice();
            selecionadoVersaoOffice =  listaDoOffice.get(TodosOffice.getSelectedRow());
            
            AlterarVersaoOffice alterarVersaoOffice = new AlterarVersaoOffice(selecionadoVersaoOffice,this.logado);
            alterarVersaoOffice.setVisible(true);
            dispose();

        }else{
            JOptionPane.showMessageDialog(null, "Escolha alguma versão do Office listada na tabela para alterá-la!");
        };
        
    }//GEN-LAST:event_jButtonAlterarActionPerformed

       ArrayList<VersaoOffice> listaDoOffice;
    
    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarActionPerformed
        try {
            
            VersaoOffice filtroVersaoOffice = new VersaoOffice();
            
            if(campoListar.getText().trim().equals("")==false){
            filtroVersaoOffice.setDescricao(campoListar.getText());
            }else{
                filtroVersaoOffice.setDescricao("");
            }
                                             
            
           
            listaDoOffice = Fachada.getInstancia().listarVersaoOffice(filtroVersaoOffice);
            
            DefaultTableModel tabelaOffice = new DefaultTableModel();
            tabelaOffice.setColumnIdentifiers(new String [] {"Descrição do Pacote Office"});
            
            for (VersaoOffice este: listaDoOffice){
                tabelaOffice.addRow(new String [] { este.getDescricao()});
            }
            
            TodosOffice.setModel(tabelaOffice);                                 
           
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Erro ao listar - "  + e.getMessage());
        }
    }//GEN-LAST:event_jButtonListarActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        if(TodosOffice.getSelectedRow()>=0){
        VersaoOffice removerVersaoOffice = new VersaoOffice();
        removerVersaoOffice=listaDoOffice.get(TodosOffice.getSelectedRow());
        
        if ( JOptionPane.showConfirmDialog(new JFrame(), 
       "Tem certeza que deseja remover esta versão do Office("+removerVersaoOffice.getDescricao()+")? \n(É necessário que nenhum usuário possua esta versão do Office)", 
       "Remover versão do Office", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) { 
          try {
   
    int selectedrow=(TodosOffice.getSelectedRow());
    Fachada.getInstancia().removerVersaoOffice(removerVersaoOffice);
    
        JOptionPane.showMessageDialog(null,"Versão do Office removida com sucesso!");
        
        
    listaDoOffice.remove(selectedrow);
                DefaultTableModel tabelaVersaoOffice = new DefaultTableModel();
                tabelaVersaoOffice.setColumnIdentifiers(new String [] {"Descrição do Pacote Office"});
                    //varrendo o ArrayList de Funcionário e colocando cada objeto funcionário em uma linha
                 for (VersaoOffice este: listaDoOffice){
                tabelaVersaoOffice.addRow(new String [] { este.getDescricao()});
            }
            
            TodosOffice.setModel(tabelaVersaoOffice);  
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
      } 
      else { 
            
          JOptionPane.showMessageDialog(rootPane,"Operação cancelada.");   
          return; 
      } 
        }else{
       
                JOptionPane.showMessageDialog(rootPane,"Escolha alguma Versão do Office da lista para removê-la.");
            }
 
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaPrincipal inicial= new TelaPrincipal(this.logado);  
        inicial.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void campoListarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoListarKeyPressed
        int key=evt.getKeyCode();       
        if(key==KeyEvent.VK_ENTER)
        { 
            jButtonListar.doClick();
        }
    }//GEN-LAST:event_campoListarKeyPressed

    private void jButtonCadastrarNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarNovaActionPerformed
        CadastrarVersaoOffice cadastrar = new CadastrarVersaoOffice(this.logado);
        cadastrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCadastrarNovaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarVersaoOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarVersaoOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarVersaoOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarVersaoOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarVersaoOffice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TodosOffice;
    private javax.swing.JTextField campoListar;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCadastrarNova;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
